### ISSUE TITLE
请问这个能正常运行吗？

### ISSUE THREAD

**Issue by lydemo** [CuiYongen/DuplicateChecking#1]
可以进入到主页面，但是点击上传文件就出错了，显示web_mod.upload_file()
AttributeError: 'module' object has no attribute 'upload_file'

**Comment by CuiYongen** [comment]
还在开发阶段…… 这个查重系统需要自建论文库，学校内查用的

**Comment by xhcsn** [comment]
> 还在开发阶段…… 这个查重系统需要自建论文库，学校内查用的

数据库自己建的吗...有没有知网的数据库接口啊，找了好久

**Comment by CuiYongen** [comment]
> > 还在开发阶段…… 这个查重系统需要自建论文库，学校内查用的
> 
> 数据库自己建的吗...有没有知网的数据库接口啊，找了好久

这个相当于学校内查，自建库，都是自己学校或者学院的论文。
知网数据库不会轻易开放的，不然怎么赚钱……
而且普通客户端一台机器不可能用知网的库算的，一篇一天可能都算不完……

**Comment by xhcsn** [comment]
> > > 还在开发阶段…… 这个查重系统需要自建论文库，学校内查用的
> > 
> > 
> > 数据库自己建的吗...有没有知网的数据库接口啊，找了好久
> 
> 这个相当于学校内查，自建库，都是自己学校或者学院的论文。
> 知网数据库不会轻易开放的，不然怎么赚钱……
> 而且普通客户端一台机器不可能用知网的库算的，一篇一天可能都算不完……

我想多了。。。过于naive
