### ISSUE TITLE
有联系方式么  

### ISSUE THREAD

**Issue by sankeyou123** [CuiYongen/DuplicateChecking#5]
想问一下联系方式，付费完善该项目

**Comment by CuiYongen** [comment]
18701312073，加什么都可以

不过最近可能比较忙，您可以大概说下需求（使用场景）和截止时间，我看是自己来还是协助您联系外包，如果是需要找外包我肯定尽量让您少吃亏

外包现在普遍价格在 500/人/天，如果还需要部署服务器之类的可能还给您报两个人的价（但这个项目目前为止其实基本没有服务端代码），就比较亏，所以最终还是结合您需求

我自己来的话就是相对熟悉点儿，少点儿读代码的时间，不过现在也没做技术，没怎么做正规项目了，开发上限不高（功能复杂了可能实力不行，实话实说。。）



***@***.***
 
发件人： sankeyou123
发送时间： 2022-04-16 23:31
收件人： CuiYongen/DuplicateChecking
抄送： Subscribed
主题： [CuiYongen/DuplicateChecking]有联系方式么 (Issue #5)
想问一下联系方式，付费完善该项目

**Comment by CuiYongen** [comment]
![44_6c79f43f83a514e06539bc8630a7c0c0](https://user-images.githubusercontent.com/12591929/163683966-7a4a3e32-9e3b-46df-bce7-de67c7e3f268.png)

也可以先发邮件看看需求 CuiYongen@aliyun.com
